services:
  payload:
    platform: linux/amd64
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./database:/app/database
      - payload_media:/app/media

volumes:
  payload_db:
  payload_media:
